name: "ci"

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        uses: reviewdog/action-shellcheck@v1
        with:
          check_all_files_with_shebangs: "true"

  Spec:
    uses: "puppetlabs/cat-github-actions/.github/workflows/module_ci.yml@main"
    secrets: "inherit"
